// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'

// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// // ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBvzTzL8q00wZEc4UrEZklKm_dVP3RHml8',
//     appId: '1:596998816396:android:7c4a4607d548e3f879f1a9',
//     messagingSenderId: '596998816396',
//     projectId: 'kalorien-75581',
//     databaseURL:
//         'https://kalorien-75581-default-rtdb.europe-west1.firebasedatabase.app',
//     storageBucket: 'kalorien-75581.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCOcT24hnJi2GjCV1BPIgviQup-2XQyEI4',
//     appId: '1:596998816396:ios:74dd4c029aa0cfea79f1a9',
//     messagingSenderId: '596998816396',
//     projectId: 'kalorien-75581',
//     databaseURL:
//         'https://kalorien-75581-default-rtdb.europe-west1.firebasedatabase.app',
//     storageBucket: 'kalorien-75581.appspot.com',
//     iosClientId:
//         '596998816396-4ev4fo7b1irb45nn4aoggojp4cobt7of.apps.googleusercontent.com',
//     iosBundleId: 'com.example.kalorientracker',
//   );
// }
