// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGGsQDeSgD2JKDIUoQIYzBGiSGRZHBhQg',
    appId: '1:543686872914:web:513e094c9227c1aaf3348b',
    messagingSenderId: '543686872914',
    projectId: 'kalorien-tracker',
    authDomain: 'kalorien-tracker.firebaseapp.com',
    databaseURL: 'https://kalorien-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kalorien-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_S_wU5BXr0ktDrL7r7IGo9Gp0hpGgov8',
    appId: '1:543686872914:android:a1d89b3f3e61a18af3348b',
    messagingSenderId: '543686872914',
    projectId: 'kalorien-tracker',
    databaseURL: 'https://kalorien-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kalorien-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9wElyWKhHimV2Rm_mw3CssRSXhX0HaVo',
    appId: '1:543686872914:ios:aa2f14880bed1a77f3348b',
    messagingSenderId: '543686872914',
    projectId: 'kalorien-tracker',
    databaseURL: 'https://kalorien-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kalorien-tracker.appspot.com',
    iosClientId: '543686872914-14e49fsimg2m33ca916dbe84nf5qbv7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalorientracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9wElyWKhHimV2Rm_mw3CssRSXhX0HaVo',
    appId: '1:543686872914:ios:aa2f14880bed1a77f3348b',
    messagingSenderId: '543686872914',
    projectId: 'kalorien-tracker',
    databaseURL: 'https://kalorien-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kalorien-tracker.appspot.com',
    iosClientId: '543686872914-14e49fsimg2m33ca916dbe84nf5qbv7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalorientracker',
  );
}
